<?php

namespace Archer\MeetEntryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AthleteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AthleteRepository extends EntityRepository
{
}
